### ISSUE TITLE
Implementare UC ricerca per targa o modello

### ISSUE THREAD

**Issue by nicoloabatecola** [daniele-bit/garage-esercitazione#7]

**Comment by daniele-bit** [comment]
Risolto lato server con commit 6862bbd1f07f811d3fcdb663be3f23b26e2be15c. Ancora da terminare lato Client

**Comment by nicoloabatecola** [comment]
Risolto lato client con commit 4b1e80b85f5dc14074bc5bc1779f03ac391cf4d5
